site_name: DemoOS documentation
site_url: https://github.com/andrearanica/demoos

docs_dir: docs 

nav:
  - Home: index.md
  - Installation: installation.md
  - Functionalities: functionalities.md
  - Code structure: code.md

theme:
  name: readthedocs
